openapi: "3.0.0"
info:
  version: 1.0.0
  title: Faraday API
  license:
    name: GPLv3
servers:
  - url: https://cloud.faradaysec.com

paths:
  /ws:
    get:
      summary: List all workspaces
      responses:
        '200':
          description: An array of workspaces
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workspace"
components:
  schemas:
    Workspace:
      type: object
      required:
        - _id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
